#!/usr/bin/env bash
# ============================================================
# 02-master.sh — Chạy trên MASTER NODE
# Cài: kubeadm init → Cilium → MetalLB
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config.env"

# ── Colors ──────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
BLUE='\033[0;34m'; CYAN='\033[0;36m'; NC='\033[0m'

info()    { echo -e "${CYAN}[INFO]${NC}  $*"; }
success() { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }
step()    { echo -e "\n${BLUE}══════════════════════════════════════${NC}"; \
            echo -e "${BLUE}  $*${NC}"; \
            echo -e "${BLUE}══════════════════════════════════════${NC}"; }

wait_pods_ready() {
    local ns="$1" label="$2" timeout="${3:-120}"
    info "Chờ pods ready: namespace=$ns label=$label ..."
    kubectl wait --namespace "$ns" \
        --for=condition=ready pod \
        --selector="$label" \
        --timeout="${timeout}s"
}

# ── Guard ────────────────────────────────────────────────────
[[ $EUID -ne 0 ]] && error "Phải chạy với quyền root: sudo bash $0"

# Kiểm tra đã chạy 01-prepare.sh chưa
command -v kubeadm &>/dev/null || error "kubeadm không tìm thấy. Chạy 01-prepare.sh trước."
command -v containerd &>/dev/null || error "containerd không tìm thấy. Chạy 01-prepare.sh trước."

# ============================================================
step "PHASE 1 — kubeadm init"
# ============================================================

# Nếu cluster đã tồn tại thì bỏ qua
if kubectl cluster-info &>/dev/null 2>&1; then
    warn "Cluster đã tồn tại, bỏ qua kubeadm init"
else
    info "Khởi tạo control plane tại $MASTER_IP ..."
    kubeadm init \
        --apiserver-advertise-address="$MASTER_IP" \
        --control-plane-endpoint="$MASTER_IP:6443" \
        --pod-network-cidr="$POD_CIDR" \
        --service-cidr="$SERVICE_CIDR" \
        --skip-phases=addon/kube-proxy \
        --node-name="$MASTER_HOSTNAME"

    success "kubeadm init hoàn thành"
fi

# ── Setup kubectl cho root ───────────────────────────────────
mkdir -p /root/.kube
cp -f /etc/kubernetes/admin.conf /root/.kube/config
chown root:root /root/.kube/config
export KUBECONFIG=/root/.kube/config

# Setup kubectl cho user thường (nếu có $SUDO_USER)
if [[ -n "${SUDO_USER:-}" ]]; then
    USER_HOME=$(getent passwd "$SUDO_USER" | cut -d: -f6)
    mkdir -p "$USER_HOME/.kube"
    cp -f /etc/kubernetes/admin.conf "$USER_HOME/.kube/config"
    chown "$SUDO_USER:$SUDO_USER" "$USER_HOME/.kube/config"
    info "kubectl config copied to $USER_HOME/.kube/config"
fi

# ── Cho phép master chạy workload (single-node mode) ─────────
info "Removing master taint để có thể chạy pods trên master..."
kubectl taint nodes "$MASTER_HOSTNAME" node-role.kubernetes.io/control-plane:NoSchedule- 2>/dev/null || true

# ── Tạo join command ─────────────────────────────────────────
step "Tạo worker join command"
JOIN_CMD=$(kubeadm token create --print-join-command)
echo "#!/usr/bin/env bash" > "$JOIN_CMD_FILE"
echo "# Auto-generated by 02-master.sh — $(date)" >> "$JOIN_CMD_FILE"
echo "$JOIN_CMD --node-name \"\$(hostname)\"" >> "$JOIN_CMD_FILE"
chmod +x "$JOIN_CMD_FILE"

success "Join command saved: $JOIN_CMD_FILE"
info "Nội dung join command:"
cat "$JOIN_CMD_FILE"

# ============================================================
step "PHASE 2 — Cài Cilium CLI"
# ============================================================
if command -v cilium &>/dev/null; then
    warn "cilium CLI đã có: $(cilium version --client 2>/dev/null | head -1)"
else
    info "Downloading Cilium CLI $CILIUM_CLI_VERSION ..."
    curl -fsSL --retry 3 \
        "https://github.com/cilium/cilium-cli/releases/download/${CILIUM_CLI_VERSION}/cilium-linux-amd64.tar.gz" \
        -o /tmp/cilium-cli.tar.gz
    tar xzf /tmp/cilium-cli.tar.gz -C /tmp
    mv /tmp/cilium /usr/local/bin/cilium
    chmod +x /usr/local/bin/cilium
    rm -f /tmp/cilium-cli.tar.gz
    success "cilium CLI installed: $(cilium version --client 2>/dev/null | head -1)"
fi

# ============================================================
step "PHASE 3 — Deploy Cilium CNI"
# ============================================================
info "Installing Cilium $CILIUM_VERSION (kube-proxy replacement mode)..."

cilium install \
    --version "$CILIUM_VERSION" \
    --set kubeProxyReplacement=true \
    --set k8sServiceHost="$MASTER_IP" \
    --set k8sServicePort=6443 \
    --set ipam.mode=kubernetes \
    --set routingMode=tunnel \
    --set tunnelProtocol=vxlan \
    --set nodeinit.enabled=true \
    --set hostServices.enabled=true \
    --set externalIPs.enabled=true \
    --set nodePort.enabled=true

info "Chờ Cilium ready (tối đa 3 phút)..."
cilium status --wait --wait-duration 3m

success "Cilium deployed"
cilium status

# ── Verify nodes ready sau khi có CNI ───────────────────────
info "Kiểm tra nodes..."
kubectl wait --for=condition=Ready node --all --timeout=120s
kubectl get nodes -o wide

# ============================================================
step "PHASE 4 — Deploy MetalLB"
# ============================================================
info "Applying MetalLB $METALLB_VERSION ..."
kubectl apply -f \
    "https://raw.githubusercontent.com/metallb/metallb/${METALLB_VERSION}/config/manifests/metallb-native.yaml"

info "Chờ MetalLB controller ready (tối đa 2 phút)..."
kubectl wait --namespace metallb-system \
    --for=condition=ready pod \
    --selector=app=metallb,component=controller \
    --timeout=120s

success "MetalLB controller ready"

# ── Cấu hình IP pool ─────────────────────────────────────────
info "Cấu hình MetalLB IP pool: $METALLB_IP_RANGE"

cat > /tmp/metallb-config.yaml << EOF
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
spec:
  addresses:
  - ${METALLB_IP_RANGE}
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - default-pool
EOF

# MetalLB CRDs cần vài giây để register sau khi apply
sleep 10
kubectl apply -f /tmp/metallb-config.yaml
success "MetalLB IP pool configured: $METALLB_IP_RANGE"

# ============================================================
step "PHASE 5 — Test LoadBalancer service"
# ============================================================
info "Deploy nginx test để verify MetalLB..."

cat > /tmp/test-lb.yaml << 'EOF'
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test-lb
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: nginx-test
  ports:
  - port: 80
    targetPort: 80
EOF

kubectl apply -f /tmp/test-lb.yaml

info "Chờ nginx pod ready..."
kubectl wait --for=condition=ready pod -l app=nginx-test --timeout=60s

info "Chờ LoadBalancer IP được gán (30s)..."
sleep 30

LB_IP=$(kubectl get svc nginx-test-lb -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null || echo "")

if [[ -n "$LB_IP" ]]; then
    success "MetalLB assigned IP: $LB_IP"
    if curl -sf --max-time 5 "http://$LB_IP" &>/dev/null; then
        success "nginx test PASSED — LoadBalancer hoạt động!"
    else
        warn "nginx unreachable từ host. Có thể do VMware network — kiểm tra thủ công."
    fi
else
    warn "LoadBalancer IP chưa được gán. Kiểm tra: kubectl get svc nginx-test-lb"
fi

# Cleanup test
kubectl delete -f /tmp/test-lb.yaml 2>/dev/null || true

# ============================================================
step "PHASE 6 — Final status"
# ============================================================
echo ""
info "=== Cluster Nodes ==="
kubectl get nodes -o wide

echo ""
info "=== System Pods ==="
kubectl get pods -A

echo ""
info "=== Storage Classes ==="
kubectl get storageclass 2>/dev/null || true

echo ""
echo -e "${GREEN}╔═══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║  02-master.sh HOÀN THÀNH                     ║${NC}"
echo -e "${GREEN}╚═══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}Bước tiếp theo — Trên từng WORKER node:${NC}"
echo ""
echo -e "  1. Copy join command:"
echo -e "     ${CYAN}scp root@${MASTER_IP}:${JOIN_CMD_FILE} /tmp/k8s-join.sh${NC}"
echo ""
echo -e "  2. Chạy trên worker:"
echo -e "     ${CYAN}sudo bash 03-worker.sh${NC}"
echo ""
echo -e "  3. Sau khi tất cả workers join, kiểm tra trên master:"
echo -e "     ${CYAN}kubectl get nodes${NC}"
