apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kiểm tra version mới nhất: https://github.com/kubevirt/kubevirt/releases
# Thay v1.4.0 bằng version muốn dùng
resources:
  - https://github.com/kubevirt/kubevirt/releases/download/v1.4.0/kubevirt-operator.yaml
  - kubevirt-cr.yaml
